CREATE TABLE [Harsco].[DimCustomerLocation] (
    [CustomerLocationKey]    INT            IDENTITY (1, 1) NOT NULL,
    [CustomerKey]            INT            NOT NULL,
    [CustomerLocationNumber] NVARCHAR (100) NULL,
    [CustomerLocationName]   NVARCHAR (100) NULL,
    [Address1]               VARCHAR (200)  NULL,
    [Address2]               VARCHAR (200)  NULL,
    [Address3]               VARCHAR (200)  NULL,
    [City]                   VARCHAR (200)  NULL,
    [State]                  VARCHAR (200)  NULL,
    [PostalCode]             VARCHAR (200)  NULL,
    [Province]               VARCHAR (200)  NULL,
    [PaymentTermsKey]        INT            NULL,
    [CustomerSiteLocCode]    INT            NULL,
    [CustomerSiteLocName]    VARCHAR (200)  NULL,
    [CustomerProfileClass]   VARCHAR (200)  NULL,
    [Tolerance]              VARCHAR (200)  NULL,
    [CreditChecking]         VARCHAR (200)  NULL,
    [CreditHold]             VARCHAR (200)  NULL,
    [DiscountCode]           VARCHAR (200)  NULL,
    [LTTLSurcharge]          VARCHAR (200)  NULL,
    [Country]                VARCHAR (200)  NULL,
    [CreatedDateTime]        DATETIME       NULL,
    [LastUpdatedDateTime]    DATETIME       NULL,
    [EffectiveStartDate]     DATETIME       NOT NULL,
    [EffectiveEndDate]       DATETIME       NULL,
    [CurrentRecordIndicator] BIT            NULL,
    [AuditKey]               INT            NULL,
    [SourceSystemID]         INT            NULL,
    PRIMARY KEY CLUSTERED ([CustomerLocationKey] ASC)
);

