CREATE TABLE [Harsco].[FactARInvoices] (
    [InvoiceKey]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CustomerTransactionID]     NVARCHAR (100)  NULL,
    [OrganizationKey]           BIGINT          NULL,
    [GeneralLedgerDateKey]      INT             NULL,
    [InvoiceDateKey]            BIGINT          NULL,
    [InvoiceDueDateKey]         BIGINT          NULL,
    [ExchangeRateKey]           BIGINT          NULL,
    [AccountCustomerKey]        INT             NULL,
    [BillToCustomerLocationKey] INT             NULL,
    [ShipToCustomerLocationKey] INT             NULL,
    [PaymentTermsKey]           INT             NULL,
    [LocalCurrencyCode]         NVARCHAR (50)   NULL,
    [InvoiceCurrencyCode]       NVARCHAR (50)   NULL,
    [LocalExchangeRate]         FLOAT (53)      NULL,
    [InvoiceNumber]             NVARCHAR (50)   NULL,
    [InvoiceID]                 NVARCHAR (100)  NULL,
    [SalesOrderNumber]          NVARCHAR (50)   NULL,
    [PurchaseOrderNumber]       NVARCHAR (50)   NULL,
    [InvoiceType]               NVARCHAR (50)   NULL,
    [ReceivableType]            NVARCHAR (50)   NULL,
    [InvoiceStatus]             NVARCHAR (50)   NULL,
    [ReasonCode]                NVARCHAR (50)   NULL,
    [Comments]                  NVARCHAR (1775) NULL,
    [LocalInvoiceAmount]        NUMERIC (38, 4) NULL,
    [InvoiceAmount]             NUMERIC (38, 4) NULL,
    [InvoiceAmountUSD]          NUMERIC (38, 4) NULL,
    [CreatedDateTime]           DATETIME        NULL,
    [LastUpdatedDateTime]       DATETIME        NULL,
    [EffectiveStartDate]        DATETIME        NULL,
    [EffectiveEndDate]          DATETIME        NULL,
    [CurrentRecordIndicator]    BIT             NULL,
    [AuditKey]                  INT             NULL,
    [SourceSystemID]            INT             NULL,
    CONSTRAINT [PK_FactARInvoices] PRIMARY KEY CLUSTERED ([InvoiceKey] ASC)
);

