CREATE TABLE [Harsco].[FactARAging] (
    [ARAgingKey]             INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceKey]             INT             NOT NULL,
    [AgingType]              NVARCHAR (50)   NOT NULL,
    [AsOfDate]               NVARCHAR (100)  NULL,
    [AgingDateKey]           INT             NULL,
    [ExchangeRateKey]        INT             NULL,
    [LocalCurrencyCode]      NVARCHAR (50)   NULL,
    [InvoiceCurrencyCode]    NVARCHAR (50)   NULL,
    [ReceiptCurrencyCode]    NVARCHAR (50)   NULL,
    [AdjustmentCurrencyCode] NVARCHAR (50)   NULL,
    [TotalOpenAmount]        NUMERIC (38, 4) NULL,
    [CurrentAmount]          NUMERIC (38, 4) NULL,
    [PastDue30]              NUMERIC (38, 4) NULL,
    [PastDue60]              NUMERIC (38, 4) NULL,
    [PastDue90]              NUMERIC (38, 4) NULL,
    [PastDue120]             NUMERIC (38, 4) NULL,
    [PastDue150]             NUMERIC (38, 4) NULL,
    [PastDue151PLUS]         NUMERIC (38, 4) NULL,
    [CreatedDateTime]        DATETIME        NULL,
    [LastUpdatedDateTime]    DATETIME        NULL,
    [EffectiveStartDate]     DATETIME        NOT NULL,
    [EffectiveEndDate]       DATETIME        NULL,
    [CurrentRecordIndicator] BIT             NULL,
    [AuditKey]               INT             NULL,
    [SourceSystemID]         INT             NULL,
    PRIMARY KEY CLUSTERED ([ARAgingKey] ASC)
);

