
CREATE   VIEW [Harsco].[vDimDateAsOf]
AS
SELECT D1.DATEKEY AS ASOFDT
	FROM HARSCO.DIMDATE D1
	WHERE D1.FULLDATE IN
	(
	SELECT DISTINCT D.MONTHBEGINDATE FROM HARSCO.DIMDATE D
	WHERE D.FULLDATE < CAST(GETDATE() AS DATE)
	AND D.DATEKEY>20170101
	)
	
/****** Script for Asof dynamic selction in merge procedure ******/

