

/****** Script for SelectTopNRows command from SSMS  ******/
create   view [Harsco].[vDimDate]
as

SELECT  [DateKey]
      --,[DateType] as [Date]
      ,[FullDate] as [Date]
      ,[YearNum] as [Year]
     -- ,[YearBeginDate]
     -- ,[YearEndDate]
      ,[DayNumOfWeek] as [Day Num of Week]
     -- ,[DayNumOfMonth]
     -- ,[DayNumOfQuarter]
     -- ,[DayNumOfYear]
      ,[DayOfWeekName] as [Day of Week]
      ,[DayOfWeekAbbreviation] as [Day of Week Abbrev]
      --,[JulianDayNumOfYear]
      ,[JulianJDEDate] as [Julian JDE Date]
     -- ,[IsWeekday] as [Is Weekay]
     -- ,[IsFederalUSHoliday]
      ,[HolidayDescription] as [Holiday]
     -- ,[IsLastDayOfWeek]
    --  ,[IsLastDayOfMonth]
     -- ,[IsLastDayOfQuarter]
    --  ,[IsLastDayOfYear]
    --  ,[WeekOfYearBeginDate]
      --,[WeekOfYearEndDate]
      --,[WeekOfMonthBeginDate]
      --,[WeekOfMonthEndDate]
      --,[WeekOfQuarterBeginDate]
      --,[WeekOfQuarterEndDate]
      --,[WeekNumOfMonth]
      --,[WeekNumOfQuarter]
      --,[WeekNumOfYear]
      ,[MonthName] as [Month]
      ,[MonthNameAbbreviation] as [Month Short]
,[MonthNameAbbreviation] + ' ' + cast([DayNumOfMonth] as nvarchar(10)) as [Month-Day]
, case when datekey = -1 then '' else 
cast([DayNumOfMonth] as nvarchar(10))  + ' ' + [MonthNameAbbreviation] + ' ' + cast([yearnum] as nvarchar(5)) 
end
as [Day-Month-Year]

    --  ,[MonthBeginDate] 

    --  ,[MonthEndDate]
      ,[MonthNumOfYear]
      ,[MonthFormatYYYYMM] as [YYYY/MM]
      ,[QuarterNumOfYear] as [Quarter Number]
     -- ,[QuarterBeginDate]
     -- ,[QuarterEndDate]
      ,[QuarterFormatYYYYQQ] as [YYYY/QQ]
      ,[QuarterFormatQQ] as [Quarter]
      --,[FiscalMonthOfYear]
      --,[FiscalQuarter]
      --,[FiscalYear]
      --,[FiscalYearMonthYYYYMM]
      --,[FiscalYearQuarterYYYYQQ]
  FROM [Harsco].[DimDate]