CREATE TABLE [stg].[JDE_ARInvoices] (
    [INVOICE_NO]                VARCHAR (10)  NULL,
    [Item_No]                   VARCHAR (10)  NULL,
    [INVOICE_DATE]              DATETIME2 (6) NULL,
    [GLDate]                    INT           NULL,
    [INVOICE_TYPE]              VARCHAR (2)   NULL,
    [INVOICE_DUE_DATE]          DATETIME2 (6) NULL,
    [AMOUNT]                    VARCHAR (17)  NULL,
    [AMOUNTCURRENCY]            VARCHAR (17)  NULL,
    [CURRENCY]                  VARCHAR (3)   NULL,
    [PAYMENT_TERMS]             VARCHAR (3)   NULL,
    [PAYMENT_TERMS_DESCRIPTION] VARCHAR (1)   NULL,
    [CUSTOMER_NO]               VARCHAR (10)  NULL,
    [CUSTOMER_NAME]             VARCHAR (40)  NULL,
    [COMPANY]                   VARCHAR (5)   NULL,
    [COUNTRY_ID]                VARCHAR (3)   NULL,
    [LOCATION_CODE]             VARCHAR (12)  NULL,
    [LOCATION_NAME]             VARCHAR (30)  NULL,
    [ORIGINAL_DUE_AMOUNT]       VARCHAR (17)  NULL,
    [LineageTMST]               DATETIME      NULL,
    [UpdatedLineageString]      VARCHAR (128) NULL,
    [JDECOMLibrary]             NVARCHAR (11) NULL,
    [JDEDATLibrary]             NVARCHAR (11) NULL,
    [MCCO]                      VARCHAR (5)   NULL,
    [COUNTRY]                   VARCHAR (3)   NULL,
    [SITEID]                    VARCHAR (3)   NULL,
    [LOCATION]                  VARCHAR (30)  NULL,
    [SITETYPE]                  VARCHAR (12)  NULL,
    [PaymentStatus]             VARCHAR (50)  NULL,
    [SourceSystemID]            INT           NULL,
    [RPAID2]                    VARCHAR (50)  NULL,
    [RPGLC]                     VARCHAR (4)   NULL
);

