CREATE TABLE [stg].[JDE_F1202] (
    [FLAID]                VARCHAR (8)     NULL,
    [FLCTRY]               INT             NULL,
    [FLFY]                 INT             NULL,
    [FLFQ]                 VARCHAR (4)     NULL,
    [FLLT]                 VARCHAR (2)     NULL,
    [FLSBL]                VARCHAR (8)     NULL,
    [FLCO]                 VARCHAR (5)     NULL,
    [FLAPYC]               DECIMAL (15, 2) NULL,
    [FLAN01]               DECIMAL (15, 2) NULL,
    [FLAN02]               DECIMAL (15, 2) NULL,
    [FLAN03]               DECIMAL (15, 2) NULL,
    [FLAN04]               DECIMAL (15, 2) NULL,
    [FLAN05]               DECIMAL (15, 2) NULL,
    [FLAN06]               DECIMAL (15, 2) NULL,
    [FLAN07]               DECIMAL (15, 2) NULL,
    [FLAN08]               DECIMAL (15, 2) NULL,
    [FLAN09]               DECIMAL (15, 2) NULL,
    [FLAN10]               DECIMAL (15, 2) NULL,
    [FLAN11]               DECIMAL (15, 2) NULL,
    [FLAN12]               DECIMAL (15, 2) NULL,
    [FLAN13]               DECIMAL (15, 2) NULL,
    [FLAN14]               DECIMAL (15, 2) NULL,
    [FLAPYN]               DECIMAL (15, 2) NULL,
    [FLAWTD]               DECIMAL (15, 2) NULL,
    [FLBORG]               DECIMAL (15, 2) NULL,
    [FLPOU]                DECIMAL (15, 2) NULL,
    [FLPC]                 INT             NULL,
    [FLTKER]               DECIMAL (15, 2) NULL,
    [FLBREQ]               DECIMAL (15, 2) NULL,
    [FLBAPR]               DECIMAL (15, 2) NULL,
    [FLMCU]                VARCHAR (12)    NULL,
    [FLOBJ]                VARCHAR (6)     NULL,
    [FLSUB]                VARCHAR (8)     NULL,
    [FLNUMB]               INT             NULL,
    [FLADLM]               INT             NULL,
    [FLADM]                VARCHAR (2)     NULL,
    [FLITAC]               VARCHAR (1)     NULL,
    [FLADMP]               INT             NULL,
    [FLADSN]               VARCHAR (12)    NULL,
    [FLDIR1]               VARCHAR (1)     NULL,
    [FLDSD]                NUMERIC (6)     NULL,
    [FLUSER]               VARCHAR (10)    NULL,
    [FLLCT]                NUMERIC (6)     NULL,
    [FLPID]                VARCHAR (10)    NULL,
    [FLSBLT]               VARCHAR (1)     NULL,
    [FLCRCD]               VARCHAR (3)     NULL,
    [FLUPMJ]               NUMERIC (6)     NULL,
    [FLJOBN]               VARCHAR (10)    NULL,
    [FLUPMT]               INT             NULL,
    [FLCHCD]               VARCHAR (1)     NULL,
    [FLDPCF]               VARCHAR (1)     NULL,
    [FLCBXR]               INT             NULL,
    [JDECOMLibrary]        NVARCHAR (30)   NULL,
    [JDEDATLibrary]        NVARCHAR (30)   NULL,
    [LineageTMST]          DATETIME        NULL,
    [UpdatedLineageString] VARCHAR (30)    NULL,
    [SourceSystemID]       INT             NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_JDE_F1202_01]
    ON [stg].[JDE_F1202]([SourceSystemID] ASC);

