CREATE TABLE [stg].[Oracle_HZ_PARTIES] (
    [PARTY_ID]                  NUMERIC (15)    NULL,
    [PARTY_NUMBER]              NVARCHAR (30)   NULL,
    [PARTY_NAME]                NVARCHAR (360)  NULL,
    [PARTY_TYPE]                NVARCHAR (30)   NULL,
    [VALIDATED_FLAG]            NVARCHAR (1)    NULL,
    [LAST_UPDATED_BY]           NUMERIC (15)    NULL,
    [CREATION_DATE]             DATETIME        NULL,
    [LAST_UPDATE_LOGIN]         NUMERIC (15)    NULL,
    [REQUEST_ID]                NUMERIC (15)    NULL,
    [PROGRAM_APPLICATION_ID]    NUMERIC (15)    NULL,
    [CREATED_BY]                NUMERIC (15)    NULL,
    [LAST_UPDATE_DATE]          DATETIME        NULL,
    [PROGRAM_ID]                NUMERIC (15)    NULL,
    [PROGRAM_UPDATE_DATE]       DATETIME        NULL,
    [WH_UPDATE_DATE]            DATETIME        NULL,
    [CUSTOMER_KEY]              NVARCHAR (500)  NULL,
    [TAX_NAME]                  NVARCHAR (60)   NULL,
    [PERSON_PRE_NAME_ADJUNCT]   NVARCHAR (30)   NULL,
    [PERSON_FIRST_NAME]         NVARCHAR (150)  NULL,
    [PERSON_MIDDLE_NAME]        NVARCHAR (60)   NULL,
    [PERSON_LAST_NAME]          NVARCHAR (150)  NULL,
    [PERSON_NAME_SUFFIX]        NVARCHAR (30)   NULL,
    [PERSON_TITLE]              NVARCHAR (60)   NULL,
    [PERSON_ACADEMIC_TITLE]     NVARCHAR (30)   NULL,
    [PERSON_PREVIOUS_LAST_NAME] NVARCHAR (150)  NULL,
    [KNOWN_AS]                  NVARCHAR (240)  NULL,
    [PERSON_IDEN_TYPE]          NVARCHAR (30)   NULL,
    [PERSON_IDENTIFIER]         NVARCHAR (60)   NULL,
    [GROUP_TYPE]                NVARCHAR (30)   NULL,
    [COUNTRY]                   NVARCHAR (60)   NULL,
    [ADDRESS1]                  NVARCHAR (240)  NULL,
    [ADDRESS2]                  NVARCHAR (240)  NULL,
    [ADDRESS3]                  NVARCHAR (240)  NULL,
    [ADDRESS4]                  NVARCHAR (240)  NULL,
    [CITY]                      NVARCHAR (60)   NULL,
    [POSTAL_CODE]               NVARCHAR (60)   NULL,
    [STATE]                     NVARCHAR (60)   NULL,
    [PROVINCE]                  NVARCHAR (60)   NULL,
    [STATUS]                    NVARCHAR (1)    NULL,
    [COUNTY]                    NVARCHAR (60)   NULL,
    [SIC_CODE_TYPE]             NVARCHAR (30)   NULL,
    [FISCAL_YEAREND_MONTH]      NVARCHAR (30)   NULL,
    [EMPLOYEES_TOTAL]           NUMERIC (38, 4) NULL,
    [SIC_CODE]                  NVARCHAR (30)   NULL,
    [DUNS_NUMBER]               NUMERIC (38, 4) NULL,
    [EMAIL_ADDRESS]             NVARCHAR (2000) NULL,
    [THIRD_PARTY_FLAG]          NVARCHAR (1)    NULL,
    [COMPETITOR_FLAG]           NVARCHAR (1)    NULL,
    [DUNS_NUMBER_C]             NVARCHAR (30)   NULL,
    [LineageTMST]               DATETIME        NULL,
    [UpdatedLineageString]      VARCHAR (128)   NULL,
    [D_STATUS]                  VARCHAR (1)     NULL
);

