CREATE TABLE [stg].[Oracle_ARInvoices] (
    [Customer_TRX_id]           NVARCHAR (100)  NULL,
    [INVOICE_NUMBER]            NVARCHAR (40)   NULL,
    [ReceivableType]            NVARCHAR (100)  NULL,
    [COMMENTS]                  NVARCHAR (1760) NULL,
    [GL_XLA_DATE]               DATETIME        NULL,
    [GL_DATE]                   DATETIME        NULL,
    [INVOICE_DATE]              DATETIME        NULL,
    [GL_DATE_Closed]            DATETIME        NULL,
    [Actual_DATE_Closed]        DATETIME        NULL,
    [INVOICE_TYPE]              NVARCHAR (20)   NULL,
    [INVOICE_STATUS]            NVARCHAR (50)   NULL,
    [DUE_DATE]                  DATETIME        NULL,
    [DAY_DIFF]                  NVARCHAR (40)   NULL,
    [ORIGINAL_DUE_AMOUNT]       NUMERIC (38, 4) NULL,
    [LOCAL_AMT]                 NUMERIC (38, 4) NULL,
    [CURR_CODE]                 NVARCHAR (15)   NULL,
    [INVOICE_DATE_DIFF]         NVARCHAR (40)   NULL,
    [PAYMENT_TERMS_DAYS]        NVARCHAR (15)   NULL,
    [PAYMENT_TERMS_DESCRIPTION] NVARCHAR (240)  NULL,
    [CUSTOMER_NUMBER]           NVARCHAR (30)   NULL,
    [CUSTOMER_NAME]             NVARCHAR (360)  NULL,
    [COMPANY]                   NVARCHAR (25)   NULL,
    [GL_REV_LOCATION]           NVARCHAR (25)   NULL,
    [CUST_ACCOUNT_NAME]         NVARCHAR (240)  NULL,
    [Country]                   NVARCHAR (60)   NULL,
    [ORGANIZATION_ID]           NUMERIC (15)    NULL,
    [BILL_TO_SITE_USE_ID]       NVARCHAR (60)   NULL,
    [SHIP_TO_SITE_USE_ID]       NVARCHAR (60)   NULL,
    [XLA_LINE_ID]               NVARCHAR (150)  NULL,
    [SALES_ORDER_NUM]           NVARCHAR (50)   NULL,
    [PURCHASE_ORDER_NUM]        NVARCHAR (50)   NULL,
    [SET_OF_BOOKS_ID]           NUMERIC (15)    NULL,
    [LOC_CURRENCY_CODE]         NVARCHAR (15)   NULL,
    [LOC_EXCH_RATE]             NVARCHAR (100)  NULL,
    [UNION_NO]                  NVARCHAR (4)    NULL,
    [BATCH_SOURCE_ID]           NUMERIC (15)    NULL,
    [RECV_TYPE]                 NVARCHAR (50)   NULL,
    [SELF_BILL_NO]              NVARCHAR (150)  NULL,
    [LineageTMST]               DATETIME        NULL,
    [UpdatedLineageString]      VARCHAR (128)   NULL,
    [LAST_UPDATE_DATE]          DATETIME        NULL,
    [LAST_UPDATED_BY]           NUMERIC (38, 4) NULL,
    [CREATION_DATE]             DATETIME        NULL,
    [CREATED_BY]                NUMERIC (38, 4) NULL,
    [LAST_UPDATE_LOGIN]         NUMERIC (38, 4) NULL,
    [ORGANIZATION_CODE]         NVARCHAR (3)    NULL,
    [MASTER_ORGANIZATION_ID]    NUMERIC (38, 4) NULL,
    [SourceSystemID]            INT             NULL,
    [CodeCombinationID]         NVARCHAR (50)   NULL
);

