CREATE TABLE [stg].[Oracle_ARAdjustments] (
    [COUNTRY_ID]                   NVARCHAR (60)   NULL,
    [ORGANIZATION_ID]              NVARCHAR (283)  NULL,
    [ENTITY]                       NVARCHAR (25)   NULL,
    [TRANSACTION_DATE]             DATETIME        NULL,
    [TRANSACTION_DT]               NVARCHAR (8)    NULL,
    [AppliedCustomerTransactionID] NVARCHAR (20)   NULL,
    [CustomerTransactionID]        NVARCHAR (20)   NULL,
    [TRXTYPE]                      NVARCHAR (20)   NULL,
    [ACCTD_AMOUNT_APPLIED_TO]      NUMERIC (38, 4) NULL,
    [INVOICE_NO]                   NVARCHAR (20)   NULL,
    [AMOUNT]                       NUMERIC (38, 4) NULL,
    [CURRENCY_CODE]                NVARCHAR (15)   NULL,
    [ETL_PROC_WID]                 NUMERIC (38, 4) NULL,
    [INTEGRATION_ID]               NUMERIC (38, 4) NULL,
    [W_INSERT_DT]                  DATETIME        NULL,
    [W_UPDATE_DT]                  DATETIME        NULL,
    [DELETE_FLG]                   NVARCHAR (1)    NULL,
    [SEGMENT2]                     NVARCHAR (25)   NULL,
    [LineageTMST]                  DATETIME        NULL,
    [UpdatedLineageString]         VARCHAR (128)   NULL,
    [SourceSystemID]               INT             NULL,
    [INVOICE_DATE]                 DATETIME        NULL,
    [INVOICE_TYPE]                 NVARCHAR (MAX)  NULL,
    [TRANSACTION_ID]               NVARCHAR (20)   NULL,
    [INVOICE_DT]                   NVARCHAR (8)    NULL,
    [CASH_RECEIPT_ID]              NUMERIC (15)    NULL,
    [CUSTOMER_NO]                  NVARCHAR (30)   NULL,
    [PAYMENT_STATUS]               NVARCHAR (30)   NULL,
    [TRANS_TO_RECEIPT_RATE]        NVARCHAR (100)  NULL,
    [AMOUNT_APPLIED]               NUMERIC (38, 4) NULL,
    [ACCTD_AMOUNT_APPLIED_FROM]    NUMERIC (38, 4) NULL
);

